Clean up function spacing
Quick/Nimble pull request #847
Opened 2020-12-07 04:03 UTC by they-them

I have cleaned up some of the function spacing in the code and changed a few instances of `variable != type` to `type != variable` to be more consistent.

2020-12-23 19:20 UTC, they-them commented
Hi there! Just checking in on this pull request? :-) Can it be merged?

2021-02-05 16:33 UTC, ikesyo requested changes

2021-02-05 16:33 UTC, ikesyo commented on Sources/Nimble/Expectation.swift
> +        if "" == msg.actualValue {
I believe Yoda conditions is not appropriate for Swift: https://realm.github.io/SwiftLint/yoda_condition.html

2021-02-05 16:33 UTC, ikesyo commented on Sources/Nimble/Matchers/Contain.swift
> -
These are intentional empty lines for making early exits clear.

2021-02-05 16:51 UTC, ikesyo commented
The forked repository has gone. Closing.

2021-02-05 16:51 UTC, closed without merging