Replace deprecated libswiftXCTest.dylib with libXCTestSwiftSupport.dylib
Quick/Nimble pull request #863
Opened 2021-02-18 17:37 UTC by evelynccordner

Addresses https://github.com/Quick/Nimble/issues/855 so that Nimble will compile with xcode beta 12.5.

2021-03-02 13:46 UTC, ikesyo requested changes
Could you please update remaining references as well?

- https://github.com/Quick/Nimble/blob/e4aa2014de13b90b06eaf183c67be3e390e927da/Nimble.xcodeproj/project.pbxproj#L2020
- https://github.com/Quick/Nimble/blob/e4aa2014de13b90b06eaf183c67be3e390e927da/Nimble.xcodeproj/project.pbxproj#L2106
- https://github.com/Quick/Nimble/blob/e4aa2014de13b90b06eaf183c67be3e390e927da/Nimble.xcodeproj/project.pbxproj#L2146
- https://github.com/Quick/Nimble/blob/e4aa2014de13b90b06eaf183c67be3e390e927da/Nimble.xcodeproj/project.pbxproj#L2234
- https://github.com/Quick/Nimble/blob/e4aa2014de13b90b06eaf183c67be3e390e927da/Nimble.xcodeproj/project.pbxproj#L2273

2021-03-03 15:04 UTC, ikesyo approved these changes
LGTM, thanks for the pull request! 👍

2021-03-03 15:04 UTC, merged

2021-04-22 06:52 UTC, freak4pc commented
Any chance to get a release with this? Xcode 12.5 RC 1 was out yesterday and this is blocking our test builds @ikesyo 🙏

2021-04-24 07:45 UTC, ikesyo commented
[v9.0.1](https://github.com/Quick/Nimble/releases/tag/v9.0.1) has been released, thanks for your patience.