Be more careful about threading and notifications
Quick/Nimble pull request #974
Opened 2022-03-25 21:00 UTC by johnmckerrell

Make sure that Nimble doesn't try to access notification properties from the main
thread as they may have been created on another thread and get upset
(most likely when Core Data is involved).
Fixes #973

- [x] Does this have tests?
- [ ] Does this have documentation?
- [ ] Does this break the public API (Requires major version bump)?
- [ ] Is this a new feature (Requires minor version bump)?

2022-04-14 20:54 UTC, younata commented
I'd like to get this in the next release. Approved running the tests here.

2022-04-14 23:30 UTC, younata requested changes
Thanks for your contribution!

Holding onto a stringified version of the notification, but still holding onto the notification itself for later comparison with the predicate feels like it's not the right solution here, as tests would still fail upon comparison time. I'd love it if we could do all of the comparisons necessary in the thread that actually handles and receives the notification. There's not really a good way to do this with the current signature of the `postNotifications` matcher. If `predicate` was instead `[Predicate<Notification>]` instead of `Predicate<[Notification]>`, then, when a notification is received, you could pop off a predicate, compare it, and store the result of that.

I'm curious if anyone else @Quick/core has ideas here?

2022-04-19 22:32 UTC, younata commented
This needs some more work and thought on it, and I don't want to gate v10 on it. It's definitely valuable work, but it can also wait until v11.

2022-04-28 09:38 UTC, johnmckerrell commented
Thanks for the feedback (wow, 13 days ago), I certainly don't want to dump a PR and run away but it will probably be a little while longer before I can make any further changes FYI.

2022-10-31 21:32 UTC, younata commented
Bumping this to the next (major?) release in favor of getting async/await support out the door sooner.

2023-04-11 16:06 UTC, younata commented
Hi John! After a bunch of noodling on this, I forked your fork and made a PR that includes these changes + some feedback: https://github.com/Quick/Nimble/pull/1051

This will get merged shortly. Thanks for being patient!

2023-04-11 16:06 UTC, closed without merging